name: Render Graphviz to SVG

on:
  push:
    # 任意时候 knowledge_graph.dot 发生变化就触发
    paths:
      - 'knowledge_graph.dot'

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Render DOT file to SVG
        run: |
          dot -Tsvg knowledge_graph.dot -o knowledge_graph.svg

      - name: Commit and push generated SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add knowledge_graph.svg
          git diff-index --quiet HEAD || git commit -m "chore: auto-generate SVG from DOT"
          git push
